"""add created_at column

Revision ID: 9a90be9fe4fe
Revises: 
Create Date: 2025-12-17 00:23:43.329100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a90be9fe4fe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column(
        "project",
        "created_at",
        type_=sa.DateTime(timezone=True),
        existing_type=sa.DATE()
    )
    op.alter_column(
        "issue",
        "created_at",
        type_=sa.DateTime(timezone=True),
        existing_type=sa.DATE()
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
